### ISSUE TITLE
Wrong path indicated in the beginner_training pdf

### ISSUE THREAD

**Issue by FuHsinyu** [irods/irods_training#40]
In page 18 (section 5.4) of irods_beginner_training_2024.pdf 

The path to training images is not longer in the path indicated in the example code 

" $ wget https://github.com/irods/irods_training/raw/ugm2024/beginner/training_jpgs.zip "

which returns a 404 error

**Comment by trel** [comment]
You're ahead of us!

We're finalizing the work for ugm2024 in a couple weeks, and we just haven't made that branch yet.

**Comment by trel** [comment]
We can always move branches later - I've pushed the ugm2024 branch - thank you!
