### ISSUE TITLE
inefficient chown build step for compute to data docker image

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_training#46]
docker build required in excess of two minutes to perform a simple recursive chown operation on a directory (/opt/conda in this case, for the `jupyter/base-notebook` derived image).  This is a workaround that simply copies all subpaths, from  a source tree to destination tree , with a forced ownership change. Invoking user must be root or have sudo.

**Comment by alanking** [comment]
I think our current thinking is that this improved the build time by a couple of minutes, but not enough to make the kind of impact we need.

Trying out a build from fresh now in a VM reprsentative of those used in training so we have some numbers...

**Comment by alanking** [comment]
It still took my VM almost exactly 10 minutes to build this.

**Comment by korydraughn** [comment]
Perhaps we can modify the Dockerfile so that the longest part of the build (i.e. conda) is captured in a pre-built image.

I see parts of the Dockerfile appear to be volume mountable.

**Comment by d-w-moore** [comment]
> Perhaps we can modify the Dockerfile so that the longest part of the build (i.e. conda) is captured in a pre-built image.
> 
> I see parts of the Dockerfile appear to be volume mountable.
> 
> I believe @d-w-moore mentioned the idea of a pre-built image which would serve as the base too.

I've got some changes of the type you describe in  my test container. .  It did built what seemed to be an equivalent image. I need to make a pull request from that, maybe someone can test the compute to data training with it.

**Comment by alanking** [comment]
Yes, please open a PR and I'll have a look.

**Comment by korydraughn** [comment]
@d-w-moore Good. I second what @alanking said.

**Comment by d-w-moore** [comment]
> > Yes, please open a PR and I'll have a look.

> @d-w-moore Good. I second what @alanking said.

@alanking , @korydraughn , here it is: #48

**Comment by alanking** [comment]
We decided to change the approach such that building the Docker image during the training will not be necessary. Here's the commit message describing the selected approach:

> This makes the image generic so that it may be kept at Docker Hub for
download in the compute to data training, instead of having to lead
audience through a time consuming build step.
>
> To accommodate this, we switch to docker exec as the mode for running
the jupyter notebook as well as chown and other UID/GID related pre-
and post-processing steps.  One side effect is we may now specify
a number of commands, not just one, ie a processing pipeline; and
we can specify which user runs each step.

**Comment by alanking** [comment]
Whoops, need to update the task_config.json to reflect the new image.
